const fileData = {
  data: {
    kind: "drive#file",
    fileExtension: "PDF",
    copyRequiresWriterPermission: false,
    md5Checksum: "168e8fbf6b429946af8c595abfd5bfe7",
    writersCanShare: true,
    viewedByMe: true,
    mimeType: "application/pdf",
    parents: ["1FXhe0fY89DfVJz6Dh5J7JMuzm0XwuET2"],
    thumbnailLink:
      "https://lh3.googleusercontent.com/drive-storage/AJQWtBNRvYcTGQnHzxrFbsdgbwrL_-iAOcRDmOkzHQGPF19Nim5lreHsq8AuuVrhxCwqxhJVbrHsnkYVrqiEz6RX5XXa7BSK2ZZn4tIsLJJwOHSZkig=s220",
    iconLink: "https://drive-thirdparty.googleusercontent.com/16/type/application/pdf",
    shared: true,
    lastModifyingUser: {
      displayName: "יותם מלחי",
      kind: "drive#user",
      me: true,
      permissionId: "02533419440774582257",
      emailAddress: "m.lhafakot@gmail.com",
      photoLink: "https://lh3.googleusercontent.com/a/ACg8ocJzeGfwawcXJJs4FoeqOQItYy7FEM95ZIXt0meqFsauRtdX7g=s64",
    },
    owners: [[Object]],
    headRevisionId: "0B-Gg1zOBRgC4QjRjR3Z0ZExWYjNaUUNWUDhDSXBwN0tJRjQwPQ",
    webViewLink: "https://drive.google.com/file/d/1vIuAYoKVYzHlsKe-GsN_5Excbtjda-Ls/view?usp=drivesdk",
    webContentLink: "https://drive.google.com/uc?id=1vIuAYoKVYzHlsKe-GsN_5Excbtjda-Ls&export=download",
    size: "940614",
    viewersCanCopyContent: true,
    permissions: [[Object], [Object]],
    hasThumbnail: true,
    spaces: ["drive"],
    id: "1vIuAYoKVYzHlsKe-GsN_5Excbtjda-Ls",
    name: "cad.dwfx.PDF",
    starred: false,
    trashed: true,
    explicitlyTrashed: true,
    createdTime: "2025-03-13T19:05:37.043Z",
    modifiedTime: "2025-03-19T19:43:53.292Z",
    modifiedByMeTime: "2025-03-19T19:43:53.292Z",
    viewedByMeTime: "2025-03-13T19:05:37.043Z",
    quotaBytesUsed: "940614",
    version: "5",
    originalFilename: "cad.dwfx.PDF",
    ownedByMe: true,
    fullFileExtension: "dwfx.PDF",
    isAppAuthorized: false,
    capabilities: {
      canChangeViewersCanCopyContent: true,
      canEdit: true,
      canCopy: true,
      canComment: true,
      canAddChildren: false,
      canDelete: true,
      canDownload: true,
      canListChildren: false,
      canRemoveChildren: false,
      canRename: true,
      canTrash: true,
      canReadRevisions: true,
      canChangeCopyRequiresWriterPermission: true,
      canMoveItemIntoTeamDrive: false,
      canUntrash: true,
      canModifyContent: true,
      canMoveItemOutOfDrive: false,
      canAddMyDriveParent: false,
      canRemoveMyDriveParent: true,
      canMoveItemWithinDrive: true,
      canShare: true,
      canMoveChildrenWithinDrive: false,
      canModifyContentRestriction: true,
      canChangeSecurityUpdateEnabled: false,
      canAcceptOwnership: false,
      canReadLabels: false,
      canModifyLabels: false,
      canModifyEditorContentRestriction: true,
      canModifyOwnerContentRestriction: true,
      canRemoveContentRestriction: false,
      canDisableInheritedPermissions: false,
      canEnableInheritedPermissions: true,
    },
    thumbnailVersion: "1",
    modifiedByMe: true,
    permissionIds: ["anyoneWithLink", "02533419440774582257"],
    linkShareMetadata: { securityUpdateEligible: false, securityUpdateEnabled: true },
    sha1Checksum: "549c780b87827838c8e965a7925c4bbefdfa319f",
    sha256Checksum: "d8977e8cef259a1e83f176879ec7639e572c034c3b89529c3d5094e813dca959",
    inheritedPermissionsDisabled: false,
  },
  filePermissions: [
    {
      id: "anyoneWithLink",
      type: "anyone",
      kind: "drive#permission",
      role: "reader",
      allowFileDiscovery: false,
    },
    {
      id: "02533419440774582257",
      displayName: "יותם מלחי",
      type: "user",
      kind: "drive#permission",
      photoLink: "https://lh3.googleusercontent.com/a/ACg8ocJzeGfwawcXJJs4FoeqOQItYy7FEM95ZIXt0meqFsauRtdX7g=s64",
      emailAddress: "m.lhafakot@gmail.com",
      role: "owner",
      deleted: false,
      pendingOwner: false,
    },
  ],
};
