// import type { Metadata } from "next";

// import "./globals.css";
import { getServerSession } from "next-auth";
import { options } from "./api/auth/[...nextauth]/options";
import SignIn from "./signIn/page";
// import { UpperNav } from "./_components/LogOutButton";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// http://localhost:3000/doco?tab=documents

// mailData: {
//   fromName: 'Yotam Malhi',
//   fromEmail: 'yotam@mlshop.co.il',
//   subject: 'מכבי שירותי בריאות_1742450220159.pdf יותם',
//   createdAt: 1742891589,
//   updatedAt: 1742891589,
//   id: '195b229631228cb9',
//   labelIds: [ 'SENT' ],
//   sizeEstimate: 275901,
//   snippet: 'יותם',
//   internalDate: '1742450810000',
//   exists: false,
//   filesAmount: 1,
//   filesExists: 0
// },
// date: 1742891596

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(options).then((d) => {
    if (d) {
      const { accessToken, refreshToken } = d;
      return { accessToken, refreshToken };
    }
  });

  return (
    <html dir="rtl" lang="en" suppressHydrationWarning>
      <body>{session ? children : <SignIn />}</body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
